
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ga4_mvs'
version: '0.0.1'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# N.B. materialisation settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  base:
    +docs:
      node_color: DarkGreen
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    +schema: dbt_ga4
  intermediate:
    +docs:
      node_color: SteelBlue
    +materialized: ephemeral
    +persist_docs:
      relation: true
      columns: true
    +schema: dbt_ga4
  marts:
    +docs:
      node_color: FireBrick
    +materialized: table
    +persist_docs:
      relation: true
      columns: true
    +schema: dbt_ga4

tests:
  +severity: warn


vars:
  ga4_mvs:
    # ga4_project: "infinite-library-learning-app"
    ga4_project: "dataflow-infrastructure"
    # ga4_analytics_schema: "analytics_374884044"
    ga4_analytics_schema: "analytics_263250344"
    ua_ga4_stitch_date: '1999-01-01'
