
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ga4_mvs'
version: '0.0.1'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# N.B. materialisation settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  ga4_base:
    +docs:
      node_color: DarkGreen
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    +schema: ga4_base
  ga4_intermediate:
    +docs:
      node_color: SteelBlue
    +materialized: ephemeral
    +persist_docs:
      relation: true
      columns: true
    +schema: ga4_intim
  ga4_marts:
    +docs:
      node_color: FireBrick
    +materialized: table
    +persist_docs:
      relation: true
      columns: true
    +schema: ga4_marts

tests:
  +severity: warn


vars:
  ga4_mvs:
    example_var: DATE('2023-01-01')
